'use client';

import React, { useEffect } from 'react';
import Head from 'next/head';

const Header = ({ title }) => {
  useEffect(() => {
    document.title = title;
  }, [title]);

  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>
  );
};

export default Header;
